#!/usr/bin/env python
#http://blog.engledew.com/post/344116035/absolute-paths-from-relative-paths-in-bash
import os, sys
if len(sys.argv) < 2:
    print 'usage: %s <PATHS>' % sys.argv[0]
    raise SystemExit(1)
directory = os.path.dirname(sys.argv[1])
if len(sys.argv) > 2:
    directory = os.path.join(directory, *sys.argv[2:])
print os.path.abspath(directory)
