#!/bin/bash

root=~/.encrypted
mountpoint=~/crypt

cleanup() {
    cd $root
    git add -A
    git commit -am "secret changes were made"
    git pull
    git push
    cd
    fusermount -u $mountpoint || umount $mountpoint
    echo
    echo "All done, you can press ENTER now."
    echo "(The clever exec hack is a hack)"
}

cd "$root"
printf "Syncing... "
if ! git pull; then
    echo "Pull failed" 1>&2
    exit 1
fi

fusermount -u $mountpoint 2>/dev/null
if encfs $root $mountpoint; then
    cd $mountpoint
    # note the exec is to make sure tmux see vim as the BASH_COMMAND
    # see: http://askubuntu.com/questions/247807/run-program-from-a-shell-script-but-behave-as-one-process-only
    { while kill -0 $$ 2>/dev/null; do sleep 1; done; cleanup; } & 
    exec vims diary
fi

trap SIGTERM
echo terminating...

# installation notes on mac:
# first need to in stall osxfuse: http://sourceforge.net/projects/osxfuse/files/osxfuse-2.8.3/osxfuse-2.8.3.dmg/download
# then brew (might take a while): brew install homebrew/fuse/encfs
