#!/bin/bash
# Usage: $ register-ssh username@server
# Assumes a ~/.ssh/id_rsa.pub
# And*/or a ~/.ssh/id_dsa.pub
# (*: Two is untested)
# If you don't have one see here: https://www.digitalocean.com/community/articles/how-to-set-up-ssh-keys--2
# In short:
# $ ssh-keygen -t rsa
# You'll be asked for a password, it's extra security if you lose your private key.  But of course you'll be asked for your password.
if [ -z "$1" ]; then
    echo "Usage: $0 <user@ssh.addr>" 1>&2 
    exit 1
fi

cat ~/.ssh/id_???.pub | ssh $1 "mkdir ~/.ssh;cat >> ~/.ssh/authorized_keys"
