#!/bin/sh

if [ -z "$1" ]; then
    echo "Usage $0 <host> <pem file> [session]"
    echo "  e.g. $ ssh-pem-tmux dev-machine"
    echo "       $ ssh-pem-tmux philip@dev-machine my-tmux-session-name"
    exit 1
fi

target=$1
shift
session=${1:-general}
if [ $# -gt 0 ]; then
    shift
fi

echo "Attempt to log into $target"

ssh $target $@ -t "\$HOME/bin/scripts/tmux-simple $session"
