#!/bin/sh

if [ -z "$1" ]; then
    echo "Usage $0 <host> <pem file> [session]"
    echo "  e.g. $ ssh-pem-tmux dev-machine keys.pem"
    echo "       $ ssh-pem-tmux philip@dev-machine keys.pem my-tmux-session-name"
    exit 1
fi

target=$1
shift
pem=$1
shift
session=${1:-general}
shift

echo "Attempt to log into $target"

ssh $target $@ -i $pem -t "\$HOME/bin/scripts/tmux-simple $session"
