#!/bin/sh

session=${1:-default}
vim -c "let g:session_directory = '$(g vim-sessions 2>/dev/null || printf $HOME)'|
        let g:session_autosave = 'yes'|
        let g:session_autosave_periodic = 1|
        OpenSession $session"
