#!/bin/bash

session="$1"
sessiondir="$(g vim-sessions 2> /dev/null || printf "")"
force="${2:-}"

#usage: $0 [session [!]]

if [ -z "$sessiondir" ]; then
    echo "Error: no 'vim-sessions' place defined.  (Required)" >&2
    exit 1
fi

if [ -z "$session" ]; then
    ls $(g vim-sessions) | sed -e 's/\(.*\).vim$/\1/'
    exit 0
fi


if ls $(g vim-sessions) | grep -q "$session"; then
    echo "Opening $session"
    # note the exec is to make sure tmux see vim as the BASH_COMMAND
    # see: http://askubuntu.com/questions/247807/run-program-from-a-shell-script-but-behave-as-one-process-only
    exec vim -c "let g:session_directory = '$sessiondir'|
            let g:session_autosave = 'yes'|
            let g:session_autosave_periodic = 1|
            OpenSession $session" 
else
    echo "session doesn't exist. Creating..."
    exec vim -c "let g:session_directory = '$(g vim-sessions 2>/dev/null || printf $HOME)'|
            let g:session_autosave = 'yes'|
            let g:session_autoload = 'no'|
            let g:session_autosave_periodic = 1|
            SaveSession $session"
fi

